### ISSUE TITLE
Timeline event readiness tracker

### ISSUE THREAD

**Issue by hossain-khan** [hossain-khan/github-stats#40]
List of unique event types found so far:

* [ ] `"assigned"`
* [ ] `"closed"`
* [ ] `"commented"`
* [ ] `"committed"`
* [ ] `"cross-referenced"`
* [ ] `"head_ref_deleted"`
* [ ] `"head_ref_force_pushed"`
* [ ] `"labeled"`
* [ ] `"locked"`
* [ ] `"mentioned"`
* [ ] `"merged"`
* [ ] `"milestoned"`
* [ ] `"ready_for_review"`
* [ ] `"referenced"`
* [ ] `"renamed"`
* [ ] `"review_requested"`
* [ ] `"reviewed"`
* [ ] `"subscribed"`
* [ ] `"unlabeled"`
